version: '3.8'

services:
  # Mail server for development
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - emllm-network

  # Bot that sends test emails
  bot-generator:
    build:
      context: .
      dockerfile: bot-generator/Dockerfile
    container_name: bot-generator
    user: root
    security_opt:
      - no-new-privileges:true
    env_file: .env
    depends_on:
      - mailhog
    networks:
      - emllm-network
    restart: unless-stopped

  # Main processing service
  camel-server:
    build:
      context: .
      dockerfile: camel-server/Dockerfile
    container_name: camel-server
    user: root
    security_opt:
      - no-new-privileges:true
    env_file: .env
    depends_on:
      - mailhog
      - ollama
    volumes:
      - ./config:/app/config
    networks:
      - emllm-network
    restart: unless-stopped

  # Client that receives and deploys apps
  client-agent:
    build:
      context: .
      dockerfile: client-agent/Dockerfile
    container_name: client-agent
    user: root
    security_opt:
      - no-new-privileges:true
    env_file: .env
    depends_on:
      - mailhog
    volumes:
      - ./deployment:/app/deployment
    networks:
      - emllm-network
    restart: unless-stopped

  # LLM service (optional)
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - emllm-network

  # Web interface
  web-client:
    build:
      context: .
      dockerfile: web-client/Dockerfile
    container_name: web-client
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - mailhog
    networks:
      - emllm-network
    restart: unless-stopped

networks:
  emllm-network:
    driver: bridge

volumes:
  ollama_data:
  config:
  deployment:
